### ISSUE TITLE
How do you solve the USB limit problem?

### ISSUE THREAD

**Issue by wtjin1992** [phine-eredar/asus-z370-a-ii-hackintosh#1]
I see that you only included 3 kexts in your EFI, don't you need intelmausi.kext to enable the gigabyte internet? And how did you solve the USB limit problem. I am planing to build a hackintosh with the same motherboard, thanks for any help

**Comment by phine-eredar** [comment]
Ethernet: I need WiFi for various Apple features, like AirDrop, and my WiFi connection is good (I am set up very close to my base station). I’m also trying to both minimize the number of Kexts I depend upon, and minimize the number of wires plugged into my machine. So for me, the conclusion I came to was to use WiFi exclusively for my internet connection. If you want Ethernet, then yes, you’ll probably need a Kext. I used to use Mausi, and it worked well.

Usb: Back when my machine used an ITX board (Z370-I), I had to port map, or my machine would not stay asleep. For whatever reason, my ATX board seems to have no trouble going to sleep and staying that way without any port mapping. I seem to be able to use all ports. I don’t have any usb devices that would benefit from usb 3 speeds. Your mileage may vary! If you need to do port mapping, CorpNewt has a usbmap tool that is good.

Best of luck with your build! This has been a great mobo. I love that AptioMem helps it to provide native nvram, which is really helpful when there are kernel panics.

**Comment by wtjin1992** [comment]
Thanks a lot for your detailed explanation. I managed to install my hackintosh on asus prime z370-a + 8700k + rx580. Mine is also working perfectly without any port mapping stuff. All usb ports are working fine OOB. I added the Mausi kext you mentioned into my EFI folder and the ethernet is now working perfectly. Thanks for your help!
